export EDITOR="nvim"
export VISUAL="$EDITOR"

_appendToPath() {
    for dir; do
        # canonicalize sym links
        dir=$({ cd -- "$dir" && { pwd -P || pwd } } 2> /dev/null)

        # skip nonexistent directory
        if [ -z "$dir" ]; then
            continue
        fi

        case ":$PATH:" in
            *":$dir:"*) :;;

            *) PATH=$PATH:$dir;;
        esac

    done
}


# Expand $PATH to include additional paths if not already set
HOME_BIN=$HOME/bin
NPM_PACKAGES_BIN=$HOME/.npm-packages/bin
CARGO_BIN=$HOME/.cargo/bin

_appendToPath $HOME_BIN $NPM_PACKAGES_BIN $CARGO_BIN

export PATH

unset MANPATH
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
