export EDITOR="vim"
export VISUAL="$EDITOR"

export TOOLS_PATH=$HOME/Tools
export ANT_OPTS="-Dhttps.protocols=TLSv1.1,TLSv1.2"
export ANT_HOME=$TOOLS_PATH/apache-ant-1.10.5


MELD_BIN=$HOME/repos/meld/bin

PATH=$MELD_BIN:$PATH:$ANT_HOME/bin


# Expand $PATH to include additional paths if not already set
HOME_BIN=$HOME/bin
if [ -n "${PATH##*${HOME_BIN}}" -a -n "${PATH##*${HOME_BIN}:*}" ]; then
    PATH=$PATH:$HOME_BIN
fi


NPM_PACKAGES_BIN=$HOME/.npm-packages/bin
if [ -n "${PATH##*${NPM_PACKAGES_BIN}}" -a -n "${PATH##*${NPM_PACKAGES_BIN}:*}" ]; then
    PATH=$PATH:$NPM_PACKAGES_BIN
fi

export PATH

# Does ligtdm need to be in path?
#/usr/lib/lightdm/lightdm


unset MANPATH
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
