# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
DEFAULT_USER=$USER
#POWERLEVEL9K_MODE='nerdfont-complete'
#ZSH_THEME="powerlevel9k/powerlevel9k"
ZSH_THEME="spaceship-prompt/spaceship"


SPACESHIP_VI_MODE_COLOR="green"
SPACESHIP_VI_MODE_NORMAL=" \ue62b" # Vim icon
SPACESHIP_VI_MODE_INSERT=" "
SPACESHIP_TIME_SHOW="true"
SPACESHIP_TIME_COLOR="yellow"
SPACESHIP_TIME_FORMAT="%D{%H:%M:%S} %F{white}\uf073%f %F{$SPACESHIP_TIME_COLOR}%D{%d.%m.%y}%f"
SPACESHIP_EXIT_CODE_SHOW="true"
SPACESHIP_GIT_BRANCH_PREFIX="\uF126 "
SPACESHIP_GIT_STATUS_DIVERGED="%F{black}\uf074%f"
SPACESHIP_GIT_STATUS_BEHIND="%F{magenta}\uf019%f"
SPACESHIP_GIT_STATUS_AHEAD="%F{cyan}\uf093"
SPACESHIP_GIT_STATUS_ADDED="%F{green}\uf457%f"
SPACESHIP_GIT_STATUS_DELETED="%F{red}\uf014%f"
SPACESHIP_GIT_STATUS_MODIFIED="%F{blue}\uf069%f"
SPACESHIP_GIT_STATUS_RENAMED="%F{white}\uf044%f"
SPACESHIP_GIT_STATUS_STASHED="%F{white}\uf01c%f"
SPACESHIP_GIT_STATUS_UNMERGED="\ue726"
SPACESHIP_GIT_STATUS_UNTRACKED="%F{yellow}\uf4a3%f"
SPACESHIP_GIT_STATUS_PREFIX=" %F{red}\ue0b7%f"
SPACESHIP_GIT_STATUS_SUFFIX="%F{red}\ue0b5%f"
SPACESHIP_USER_SHOW="always"
SPACESHIP_DIR_COLOR="blue"
SPACESHIP_DIR_PREFIX="%F{$SPACESHIP_DIR_COLOR}\uf07c%f "
SPACESHIP_CHAR_SYMBOL="\ue601 "
SPACESHIP_NODE_SYMBOL="\ue718 "
SPACESHIP_PACKAGE_SYMBOL="\uf436 "


SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  #hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  node          # Node.js section
  #ruby          # Ruby section
  #elixir        # Elixir section
  #xcode         # Xcode section
  #swift         # Swift section
  #golang        # Go section
  #php           # PHP section
  #rust          # Rust section
  #haskell       # Haskell Stack section
  #julia         # Julia section
  #sfdx          # SFDX usernames
  docker        # Docker section
  #aws           # Amazon Web Services section
  #venv          # virtualenv section
  #conda         # conda virtualenv section
  #pyenv         # Pyenv section
  #dotnet        # .NET section
  #ember         # Ember.js section
  line_sep      # Line break
  vi_mode       # Vi-mode indicator
  char          # Prompt character
)

SPACESHIP_RPROMPT_ORDER=(
  jobs          # Background jobs indicator
  exec_time     # Execution time
  exit_code     # Exit code section
  #kubecontext   # Kubectl context section
  battery       # Battery level and status
  time          # Time stampts section
)



# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
    #git
    command-not-found
    git-extras
    svn
    extract
    gradle
    colored-man-pages
    mvn
    node
    extract
    npm
    #golang
    zsh-syntax-highlighting
    vi-mode
    ssh-agent
    ant
    #sfdx
    zsh-completions
)

autoload -U compinit && compinit

unsetopt all_export
source $ZSH/oh-my-zsh.sh


alias mvn="mvn-color"
alias gitk="gitk --all&"
alias pmd="/opt/pmd-bin-6.0.0/bin/run.sh pmd"
alias vim="nvim"

export ANT_ARGS='-logger org.apache.tools.ant.listener.AnsiColorLogger'

bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search

function vimdirdiff() {
    # Shell-escape each path:
    LEFT_DIR=$(printf '%q' "$1")
    shift

    RIGHT_DIR=$(printf '%q' "$1")
    shift

    vim $@ -c "DirDiff $LEFT_DIR $RIGHT_DIR"
}

function getWorkMachineIPOnVpn {
    local interface=${1:-tun0}
    local ipRange=$(ip -o -4 addr show $interface | awk '{print $4}')
    local ip=$(echo $ipRange | cut -f1 -d/)

    nmap -Pn -p 22 -oG - --open $ipRange --exclude $ip | awk '/22\/open/{print $2}'
}

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

# Base16 Shell
BASE16_SCHEME="eighties"
BASE16_SHELL="$HOME/dotfiles/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# sfdx autocomplete setup
SFDX_AC_ZSH_SETUP_PATH="$HOME/.cache/sfdx/autocomplete/zsh_setup"
[[ -f $SFDX_AC_ZSH_SETUP_PATH ]] && source $SFDX_AC_ZSH_SETUP_PATH

SF_AC_ZSH_SETUP_PATH="$HOME/.cache/sf/autocomplete/zsh_setup"
[[ -f $SF_AC_ZSH_SETUP_PATH ]] && source $SF_AC_ZSH_SETUP_PATH

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
SDKMAN_INIT="$SDKMAN_DIR/bin/sdkman-init.sh"
[[ -s "$SDKMAN_INIT" ]] && source "$SDKMAN_INIT"
